[package]
name = "miagobble/progression-utils"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Symbol = "miagobble/symbol@1.0.1"
Typer = "miagobble/typer@0.1.1"
Bucket = "miagobble/bucket@1.0.1"